apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: amqp
spec:
  amqp:
    example:
      url: rabbitmq.rabbit.svc.cluster.local:5672
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      # name of the exchange.
      exchangeName: new-file
      # exchange type. more info at https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges
      exchangeType: direct
      # routing key
      routingKey: all
      # optional backoff time for connection retries.
      # if not provided, default connection backoff time will be used.
      connectionBackoff:
        # duration in nanoseconds, or strings like "1s", "1m". following value is 10 seconds
        duration: 10s
        # how many backoffs
        steps: 5
        # factor to increase on each step.
        # setting factor > 1 makes backoff exponential.
        factor: 2
        jitter: 0.2
      # optional exchange settings
      # if not povided, default values will be used
      exchangeDeclare:
        durable: false
        autoDelete: false
        internal: false
        noWait: false
      # optional queue settings
      # if not povided, default values will be used
      queueDeclare:
        name: "new-files"
        durable: true
        autoDelete: false
        exclusive: true
        noWait: false
      # optional queue binding settings
      # if not povided, default values will be used
      queueBind:
        noWait: false
      # optional consume settings
      # if not povided, default values will be used
      consume:
        consumerTag: "test-consumer"
        autoAck: true
        exclusive: false
        noLocal: false
        noWait: false
      # username and password for authentication
      # use secret selectors
      auth:
        username:
          name: rabbit-creds
          key: username
        password:
          name: rabbit-creds
          key: password
