apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployments-watcher
rules:
  - verbs:
      - list
      - watch
      - create
      - update
      - get
    apiGroups:
      - apps
      - argoproj.io
    resources:
      - deployments
      - pods
      - workflows
